# Generated by Django 4.1 on 2022-11-11 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="adminlogin",
            fields=[
                (
                    "auto_increment_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
            ],
            options={"db_table": "admin_table",},
        ),
        migrations.CreateModel(
            name="courseperformance",
            fields=[
                ("updateid", models.AutoField(primary_key=True, serialize=False)),
                ("susername", models.CharField(max_length=100)),
                ("coursecode", models.CharField(max_length=100)),
                ("facultyusername", models.CharField(max_length=100)),
                ("score", models.CharField(max_length=100)),
                (
                    "Time",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
            options={"db_table": "courseperformance_table",},
        ),
        migrations.CreateModel(
            name="courses",
            fields=[
                ("course_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CORE", "CORE"),
                            ("PROFESSIONAL", "PROFESSIONAL ELECTIVE"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("SECURITY AND FORENSICS", "SECURITY AND FORENSICS"),
                            ("NETWORKING", "NETWORKING"),
                            ("APP DEVELOPMENT", "APP DEVELOPMENT"),
                        ],
                        max_length=100,
                    ),
                ),
                ("course_code", models.CharField(max_length=100, unique=True)),
                ("course_title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("courselink", models.CharField(max_length=100)),
            ],
            options={"db_table": "courses_table",},
        ),
        migrations.CreateModel(
            name="faculty",
            fields=[
                (
                    "auto_increment_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("fullname", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "MALE"), ("Female", "FEMALE")], max_length=100
                    ),
                ),
                ("dob", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("qualification", models.CharField(max_length=100)),
                ("experience", models.CharField(max_length=100)),
                ("salary", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("mobileno", models.CharField(max_length=100, unique=True)),
                ("location", models.CharField(max_length=100)),
            ],
            options={"db_table": "faculty_table",},
        ),
        migrations.CreateModel(
            name="facultycourseallocation",
            fields=[
                ("aid", models.AutoField(primary_key=True, serialize=False)),
                ("fusername", models.CharField(max_length=100)),
                ("course_code", models.CharField(max_length=100)),
                ("course_title", models.CharField(max_length=200)),
            ],
            options={"db_table": "facultycourseallocation_table",},
        ),
        migrations.CreateModel(
            name="questionbank",
            fields=[
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("EXTROVERTED", "EXTROVERTED"),
                            ("INTROVERTED", "INTROVERTED"),
                            ("SENSING", "SENSING"),
                            ("INTUITIVE", "INTUITIVE"),
                            ("THINKING", "THINKING"),
                            ("FEELING", "FEELING"),
                            ("JUDGING", "JUDGING"),
                            ("PROSPECTING", "PROSPECTING"),
                        ],
                        max_length=100,
                    ),
                ),
                ("question_id", models.AutoField(primary_key=True, serialize=False)),
                ("question_rid", models.CharField(max_length=100)),
                ("question", models.CharField(max_length=500, unique=True)),
                ("answer1", models.CharField(max_length=100)),
                ("answer2", models.CharField(max_length=100)),
                ("answer3", models.CharField(max_length=100)),
                ("answer4", models.CharField(max_length=100)),
                ("correctanswer", models.CharField(default="NA", max_length=100)),
            ],
            options={"db_table": "questionbank_table",},
        ),
        migrations.CreateModel(
            name="quiz_result",
            fields=[
                ("aid", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=100)),
                ("specialization", models.CharField(max_length=100)),
                (
                    "timestamp",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
            options={"db_table": "quizresult_table",},
        ),
        migrations.CreateModel(
            name="ratingcourse",
            fields=[
                (
                    "courserating_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("course_code", models.CharField(max_length=100)),
                ("studentusername", models.CharField(max_length=100)),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                        ],
                        max_length=100,
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=1000)),
                (
                    "ratingtime",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
            options={"db_table": "courserating_table",},
        ),
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "auto_increment_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("student_id", models.CharField(max_length=100)),
                ("fullname", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "MALE"), ("Female", "FEMALE")], max_length=100
                    ),
                ),
                ("dob", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("program", models.CharField(max_length=100)),
                ("cgpa", models.CharField(max_length=100)),
                ("backlogs", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("mobileno", models.CharField(max_length=100, unique=True)),
                ("location", models.CharField(max_length=100)),
            ],
            options={"db_table": "student_table",},
        ),
        migrations.CreateModel(
            name="studentregisteredcourses",
            fields=[
                ("regid", models.AutoField(primary_key=True, serialize=False)),
                ("susername", models.CharField(max_length=100)),
                ("course_id", models.CharField(max_length=100)),
                ("course_code", models.CharField(max_length=100)),
                ("course_title", models.CharField(max_length=100)),
                (
                    "timestamp",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
            options={"db_table": "studentregistered_table",},
        ),
    ]
