# Generated by Django 4.1 on 2022-11-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoproject", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="temp",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("sid", models.CharField(max_length=100)),
                ("sname", models.CharField(max_length=100)),
                ("a1", models.CharField(max_length=100)),
                ("a2", models.CharField(max_length=100)),
                ("a3", models.CharField(max_length=100)),
                ("a4", models.CharField(max_length=100)),
                ("b1", models.CharField(max_length=100)),
                ("b2", models.CharField(max_length=100)),
                ("b3", models.CharField(max_length=100)),
                ("b4", models.CharField(max_length=100)),
                ("c1", models.CharField(max_length=100)),
                ("c2", models.CharField(max_length=100)),
                ("c3", models.CharField(max_length=100)),
                ("c4", models.CharField(max_length=100)),
                ("d1", models.CharField(max_length=100)),
                ("d2", models.CharField(max_length=100)),
                ("d3", models.CharField(max_length=100)),
                ("d4", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=100)),
                ("specialization", models.CharField(max_length=100)),
            ],
            options={"db_table": "temp_table",},
        ),
    ]
