# Generated by Django 4.1 on 2022-11-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangoproject", "0002_temp"),
    ]

    operations = [
        migrations.RemoveField(model_name="temp", name="sid",),
    ]
